version: 2.1
orbs:
  android: circleci/android@3.0.0

jobs:
  build:
    executor: android/android
    steps:
      - checkout

      # Setup Android SDK
      - android/setup

      # Build and run unit tests
      - run:
          name: Build and Run Unit Tests
          command: ./gradlew test
