version: 2.1
jobs:
  build:
    working_directory: ~/project

    docker:
      - image: circleci/android:api-25-alpha
    environment:
        JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Configure environment variables
      - run:
          name: Configure Environment Variables
          command: |
            echo 'export ANDROID_HOME=/path/to/android-sdk' >> $BASH_ENV
            echo 'export PATH=$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH' >> $BASH_ENV
      

      # Grant execute permissions to gradlew
      - run:
          name: Grant Execute Permissions to gradlew
          command: chmod +x gradlew

      # Build and run unit tests
      - run:
          name: Build and Run Unit Tests
          command: ./gradlew test
