version: 2.1

jobs:
  build:
    working_directory: ~/project

    docker:
      - image: circleci/android:api-30

    steps:
      - checkout

      - run:
          name: Setup Android SDK
          command: sdkmanager --update

      - run:
          name: Configure Environment Variables
          command: echo 'export PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH' >> $BASH_ENV

      - run:
          name: Grant Execute Permissions to gradlew
          command: chmod +x gradlew

      - run:
          name: Run Unit Tests
          command: ./gradlew test
