version: 2.1
jobs:
  build:
    docker:
      - image: cimg/android:2023.06
    steps:
      - checkout
      - run:
            name: Grant Execute Permissions to gradlew
            command: chmod +x gradlew
      - run: ./gradlew androidDependencies
      - run: ./gradlew lint test
