version: 2.1
jobs:
  build:
    working_directory: ~/project

    docker:
      - image: circleci/android:api-30

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - run:
          name: Run Unit Tests
          command: ./gradlew test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
