version: 2.1

jobs:
  build:
    working_directory: ~/project

    docker:
      - image: circleci/android:api-30

    steps:
      - checkout

      - run:
          name: Run Unit Tests
          command: ./gradlew test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
